### PR TITLE
Is root available

### PR DESCRIPTION
**Pull request by mikeonoff09**
The method isRootAvailable was added. It returns a true when the device is rooted

### CODE REVIEW

**Comment by gokul1630** [comment]
> The method isRootAvailable was added. It returns a true when the device is rooted

Already `isRooted` method is available to check the availability of device root

**Comment by mikeonoff09** [comment]
The method `isRooted` calls the `isAccessGiven` method from the `[RootTools](https://github.com/Stericson/RootTools)` library, which `@return <code>true</code> if your app has been given root access.`

On the other side my PR, calls the `isRootAvailable` method which returns true when `@return <code>true</code> if su was found.`  ie, when the phone has been rooted

**Comment by gokul1630** [comment]
> The method `isRooted` calls the `isAccessGiven` method from the `[RootTools](https://github.com/Stericson/RootTools)` library, which `@return <code>true</code> if your app has been given root access.`
> 
> On the other side my PR, calls the `isRootAvailable` method which returns true when `@return <code>true</code> if su was found.` ie, when the phone has been rooted

Hmm, that makes sense...

**Review by gokul1630 — APPROVED** [review]

**Comment by ponces** [comment]
Could you please push this to pub.dev?
Thanks @gokul1630 !

**Comment by gokul1630** [comment]
> Could you please push this to pub.dev? Thanks @gokul1630 !

Published a new version, please check it out

**Pull request merged**
